import pandas as pd

df = pd.read_csv("iris.csv")
print("First 5 rows of the dataset:")
print(df.head())
print("\nDataset Info:")
print(df.info())        
print("\nMissing values in each column:")
print(df.isnull().sum())
print("\nNumber of duplicate rows:")
print(df.duplicated().sum())
df = df.drop_duplicates()
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
print("\nUpdated column names:")
print(df.columns)
print("\nStatistical summary of dataset:")
print(df.describe())
df.to_csv("iris_cleaned.csv", index=False)
print("\nData cleaning completed successfully!")
